version: 0.2
phases:
  pre_build:
    commands:
      - echo "Copying files to the respective S3 locations"
  build:
    commands:
      - echo "copying Aiflow DAG file to dag folder"
      - aws s3 cp food_processing_dag.py s3://food-delivery-project-airflow/dags/
      - aws s3 cp airflow_dag.py s3://food-delivery-project-airflow/dags/
      - aws s3 cp food_pro_dag.py s3://food-delivery-project-airflow/dags/
      - aws s3 cp airflow_dag_with_python_operator.py s3://food-delivery-project-airflow/dags/
      - aws s3 cp requirements.txt s3://food-delivery-project-airflow/
      - echo "copying pyspark script to s3 folder"
      - aws s3 cp pyspark_job.py s3://food-delivery-project/pyspark-scripts/
  post_build:
    commands:
      - echo "Deployment complete!"